name: Deploy - User Acceptance Testing

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Composer
        run: |
          EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          ACTUAL_CHECKSUM="$(php -r "echo hash_file('SHA384', 'composer-setup.php');")"
          if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then
              >&2 echo 'ERROR: Invalid installer checksum'
              rm composer-setup.php
              exit 1
          fi
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          rm composer-setup.php

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction --no-progress --no-suggest

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code
        run: |
          rsync -avz --delete --exclude=".env" --exclude="storage/" -e "ssh -o StrictHostKeyChecking=no -p 22" ./ root@5.75.190.46:/var/www/html/galleria_reward_points

#      Migration db
      - name: Migrate database and Add Permissions
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 root@5.75.190.46 "cd /var/www/html/galleria_reward_points && php artisan migrate --force"
          ssh -o StrictHostKeyChecking=no -p 22 root@5.75.190.46 "cd /var/www/html/galleria_reward_points && php artisan app:add-permissions-to-users"
          # Restart supervisor if it's installed (ignore error if not installed)
          ssh -o StrictHostKeyChecking=no -p 22 root@5.75.190.46 "systemctl restart supervisor || true"


